///*
// * This Java source file was generated by the Gradle 'init'
package ads.poo;

public class App {

    public static void main(String[] args) {

        carro c = new carro();
        carro d = new carro();

        System.out.println("velocidade:" + c.obterVelocidade());

        c.acelerar(10);

        System.out.println("velocidade: " + c.obterVelocidade());

        c.freiar(10);

        System.out.println("velocidade" + c.obterVelocidade());

        contador p = new contador();


    }


}
