/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {


        Aldeao a = new Aldeao(25,1,0.8);
        System.out.println(a);
        Arqueiro d = new Arqueiro(35,2,1);
        System.out.println(d);
        Cavaleiro c = new Cavaleiro(50,3,2);
        System.out.println(c);

        System.out.println(c.atacar());
        System.out.println(c.andar());
        System.out.println(d.Atacar());
        System.out.println(d.andar());
        System.out.println(a.andar());
        System.out.println(a.atacar());

    }
}
