/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {
    public static void main(String[] args) {
        Telefone a = new Telefone(10542,"1","nike",10.0,new Dimensao(1.0,5.0,3));
        Telefone r = new SemFio(45645,"78","adidas",10.0,new Dimensao(5,3,4),20,3,100);
        System.out.println(a.imprimirDados());
        System.out.println(r.imprimirDados());
    }


}
