/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Ponto d = new Ponto(10,5);
        Ponto e = new Ponto(15,20);

        double distancia = d.distanciaPontos(e);

        System.out.printf("%.2f\n",distancia);
        System.out.println(d);
        System.out.println(e);
    }
}
